# Generated by Django 6.0.1 on 2026-02-03 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('stream', models.CharField(blank=True, choices=[('SCIENCE', 'Science'), ('COMMERCE', 'Commerce'), ('ARTS', 'Arts'), ('NONE', 'None')], default='NONE', max_length=10, null=True)),
            ],
            options={
                'ordering': ['class_number', 'division'],
                'unique_together': {('class_number', 'division', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('parent_phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('class_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.classdivision')),
            ],
            options={
                'unique_together': {('roll_no', 'class_division')},
            },
        ),
    ]
